### ISSUE TITLE
Why not have a latest tag that points to the latest version?

### ISSUE THREAD

**Issue by uccmen** [amaysim-au/docker-serverless#17]
So I don't have to explicitly specify version when doing a docker run

**Comment by conormiley** [comment]
Hey @uccmen, thanks for the push on this. Updated to the latest version 1.26.1 of Serverless Framework.

**Comment by uccmen** [comment]
hey @conormiley - I don't think this is fixed. there still isnt a latest tag.

<img width="477" alt="screen shot 2018-05-10 at 12 32 12 pm" src="https://user-images.githubusercontent.com/1238697/39852328-887838da-544e-11e8-8b34-5a70b367b882.png">
