### ISSUE TITLE
Chore: Github actions isn't executing due to lack of activity

### ISSUE THREAD

**Issue by adveres** [amaysim-au/docker-serverless#45]
https://github.com/amaysim-au/docker-serverless/actions/workflows/deploy.yml

> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days.

-----

Serverless `2.53.X` is out, but the [latest docker image available](https://hub.docker.com/r/amaysim/serverless/tags?page=1&ordering=last_updated) is `2.44.0` from 2 months ago.

```
sls --version
Framework Core: 2.53.1
Plugin: 5.4.3
SDK: 4.2.6
Components: 3.14.2
```

Please manually re-execute the actions, or make some change so the action runs?

Thanks for the image! This is very helpful.

**Comment by flemay** [comment]
Good day, @adveres ! Sorry for the very late reply! You are correct. GitHub Actions now shows a button to continue the schedule after 60 days of inactivity. However, the current build is failing. I will fix this soon. Cheers!
