### ISSUE TITLE
As node:lts-alpine moved to version 3.14, package python does not exist anymore

### ISSUE THREAD

**Issue by flemay** [amaysim-au/docker-serverless#46]
Node Docker moved from Alpine `3.11` to `3.14` (for `node:lts-alpine`) and the later does not support `add python`. So the change is to use package `python2` instead.

The commit is https://github.com/amaysim-au/docker-serverless/commit/7dc4bfc470ac1cb4607acc931fea0a7987454d7a. I was meant to create a PR.

The commit above also makes sure the latest version of `node:lts-alpine` is downloaded.

**Comment by ypxing** [comment]
resolved by the PR mention above.
