### ISSUE TITLE
Disabled Scheduled Workflow

### ISSUE THREAD

**Issue by AlanTaranti** [amaysim-au/docker-serverless#51]
The Deploy Workflow is currently disabled because there hasn't been activity in this repository for at least 60 days.

Please see: https://github.com/amaysim-au/docker-serverless/actions/workflows/deploy.yml

![image](https://user-images.githubusercontent.com/9096525/202945665-5817e3f9-65fb-42b8-9ee0-1633662781b7.png)

**Comment by flemay** [comment]
Sorry for the very late reply @AlanTaranti. I've enabled the scheduled workflow and also built a new image for Serverless version `3.27.0`.

**Comment by AlanTaranti** [comment]
Hi @flemay, can you enable the scheduled workflow?

GitHub auto disabled it again.
