### ISSUE TITLE
Update Serverless version to 3.38

### ISSUE THREAD

**Issue by djhendry** [amaysim-au/docker-serverless#57]
3.38 of the Serverless Framework is available
https://github.com/serverless/serverless/releases/tag/v3.38.0 

The latest image version available from this repo is 3.36. 

Please can the deploy pipeline run again to create the latest version. 
https://github.com/amaysim-au/docker-serverless/actions/workflows/deploy.yml

Thank you

**Comment by flemay** [comment]
Hi! Sorry for the long wait. We just merged this [PR](https://github.com/amaysim-au/docker-serverless/pull/58) which created the image for Serverless  version `3.39.0`. This version is the last one of the major version `3`.

**Comment by djhendry** [comment]
Thank you @flemay
